ECHO OFF
REM LISEZMOI.BAT
CLS
ECHO =====================================================================
ECHO Fichier lisez-moi de la disquette avec la docum. pour CALM et ASCALM
ECHO =====================================================================
ECHO Cette disquette contient quelques fichiers batchs. Avec ces fichiers
ECHO vous pouvez imprimer les textes suivants:
ECHO ---------------------------------------------------------------------
ECHO PUBLICIT.BAT  aper‡u de CALM
ECHO ORDRE.BAT     la liste des prix, la feuille d'ordre (ASCALM, modules)
ECHO ARTICLE.BAT   explication d‚taill‚e de CALM
ECHO MANUEL.BAT    documentation complŠte de CALM et d'ASCALM
ECHO EXEMPLES.BAT  exemples pour plusieurs processeurs
ECHO DESASSEM.BAT  documentation pour le d‚sassembleur CALM
ECHO ---------------------------------------------------------------------
PAUSE pressez une touche
