// Smaky 6 — TMS2716 character generator ROM (2048 octets)
// Source : chargen_rom.h (Marcel Prisi, 2024-2026, GPL-3.0-or-later)
// Layout : 128 caractères × 16 octets. Bit 0 = pixel le plus à gauche
// (LSB-first). Les rows 8-15 servent pour les descendantes (g, j, p, q, y)
// et la barre verticale (0x7C). À interpréter selon la cellule physique
// décidée par l'électronique de balayage.
'use strict';

const CHARGEN_B64 = [
    'AAAAAAAiAAAAAAAAAAAAAAAAAHxERER8AAAAAAAAAAAAABB8VFRUfBAAAAAAAAAAAERERFRsVERE',
    'RAAAAAAAAAAEDBQkRCQUDAQAAAAAAAAAQGBQSERIUGBAAAAAAAAAABAoRER8REQoEAAAAAAAAABA',
    'SFBgfGBQSEAAAAAAAAAAEDhUEBAQEAAAAAAAAAAAAAAAIED+QCAAAAAAAAAAAAAQEBAQVDgQAAAA',
    'AAAAAAAAAAAIBP4ECAAAAAAAAAAAADgEOEREOEA4AAAAAAAAAAAAAAAAAEBAKBw+AAAAAAAAEChs',
    'KCgoKCgoAAAAAAAAKAAAREREZFgAAAAAAAAAAAgQAFhkRGRYAAAAAAAAAAAQKABYZERkWAAAAAAA',
    'AAAAIBAAOER8BDgAAAAAAAAAAAgQADhEfAQ4AAAAAAAAAAAoAAA4RHwEOAAAAAAAAAAAECgAOER8',
    'BDgAAAAAAAAAACgAABgQEBA4AAAAAAAAAAAQKAAYEBAQOAAAAAAAAAAAECgAOERERDgAAAAAAAAA',
    'AAgQAERERGRYAAAAAAAAAAAQKABERERkWAAAAAAAAAAAKAAAWGREZFgAAAAAAAAAACgAADhEREQ4',
    'AAAAAAAAAAAAAAA4RAQEeBAgEAAAAAAAAAAAUCgUKFAAAAAAAAAAAAAAABQoUCgUAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAABAQEBAQABAAAAAAAAAAAAAoKCgAAAAAAAAAAAAAAAAAKCh8KHwoKAAA',
    'AAAAAAAAABB4FDhQPBAAAAAAAAAAAAAMTCAQCGRgAAAAAAAAAAAAECgoGFQkWAAAAAAAAAAAABAQ',
    'CAAAAAAAAAAAAAAAAAAgEAgICBAgAAAAAAAAAAAACBAgICAQCAAAAAAAAAAAAAAQVDhUEAAAAAAA',
    'AAAAAAAAEBB8EBAAAAAAAAAAAAAAAAAAAAAYGBAIAAAAAAAAAAAAAHwAAAAAAAAAAAAAAAAAAAAA',
    'ABgYAAAAAAAAAAAAgEAgEAgEAgAAAAAAAAAAADhEZFRMRDgAAAAAAAAAAAAQGBAQEBA4AAAAAAAA',
    'AAAAOERAIBAIfAAAAAAAAAAAAHxAIDBARDgAAAAAAAAAAAAgMCgkfCAgAAAAAAAAAAAAfAQ8QEBE',
    'OAAAAAAAAAAAAHAIBDxERDgAAAAAAAAAAAB8QCAQCAgIAAAAAAAAAAAAOEREOEREOAAAAAAAAAAA',
    'ADhERHhAIBgAAAAAAAAAAAAAABgYABgYAAAAAAAAAAAAAAAYGAAYGBAIAAAAAAAAAEAgEAgQIEAA',
    'AAAAAAAAAAAAAHwAfAAAAAAAAAAAAAAABAgQIBAIBAAAAAAAAAAAADhEQCAQABAAAAAAAAAAAAA4',
    'RHRUdAQ4AAAAAAAAAAAAOEREfERERAAAAAAAAAAAADxERDxERDwAAAAAAAAAAAA4RAQEBEQ4AAAA',
    'AAAAAAAAPEhISEhIPAAAAAAAAAAAAHwEBDwEBHwAAAAAAAAAAAB8BAQ8BAQEAAAAAAAAAAAAOEQE',
    'BGREOAAAAAAAAAAAAERERHxEREQAAAAAAAAAAAA4EBAQEBA4AAAAAAAAAAAAcCAgICAkGAAAAAAA',
    'AAAAAEQkFAwUJEQAAAAAAAAAAAAEBAQEBAR8AAAAAAAAAAAARGxUVERERAAAAAAAAAAAAERETFRk',
    'REQAAAAAAAAAAAA4REREREQ4AAAAAAAAAAAAPEREPAQEBAAAAAAAAAAAADhERERUJFgAAAAAAAAA',
    'AAA8REQ8FCREAAAAAAAAAAAAOEQEOEBEOAAAAAAAAAAAAHwQEBAQEBAAAAAAAAAAAABEREREREQ4',
    'AAAAAAAAAAAAREREKCgQEAAAAAAAAAAAAERERFRUVCgAAAAAAAAAAABERCgQKEREAAAAAAAAAAAA',
    'REQoEBAQEAAAAAAAAAAAAHxAIBAIBHwAAAAAAAAAAABwEBAQEBBwAAAAAAAAAAAAAgQIECBAgAAA',
    'AAAAAAAAABwQEBAQEBwAAAAAAAAAAAAQKEQAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAAAAAAAAABAQ',
    'IAAAAAAAAAAAAAAAAAAAAFhkRGRYAAAAAAAAAAAABAQ0TERMNAAAAAAAAAAAAAAAOEQEBHgAAAAA',
    'AAAAAABAQFhkRGRYAAAAAAAAAAAAAAA4RHwEOAAAAAAAAAAAADBICBwICAgAAAAAAAAAAAAAAFhk',
    'RGRYQDgAAAAAAAAABAQ8RERERAAAAAAAAAAAABAAGBAQEDgAAAAAAAAAAAAgACAgICAgJBgAAAAA',
    'AAAACAhIKBgoSAAAAAAAAAAAABAQEBAQEGAAAAAAAAAAAAAAACxUVFRUAAAAAAAAAAAAAAA0TERE',
    'RAAAAAAAAAAAAAAAOERERDgAAAAAAAAAAAAAADRMREw0BAQAAAAAAAAAAABYZERkWEBAAAAAAAAA',
    'AAAANEwEBAQAAAAAAAAAAAAAAHgEOEA8AAAAAAAAAAAACAgcCAhIMAAAAAAAAAAAAAAAREREZFgA',
    'AAAAAAAAAAAAAERERCgQAAAAAAAAAAAAAABERFRUKAAAAAAAAAAAAAAARCgQKEQAAAAAAAAAAAAA',
    'AERERGRYQDgAAAAAAAAAAAB8IBAIfAAAAAAAAAAAADAICAQICDAAAAAAAAAAABAQEBAQEBAQEBAQ',
    'EBAQEBAAGCAgQCAgGAAAAAAAAAAAAAAAAEwyAAAAAAAAAAAAAAB8fHx8fHx8AAAAAAAAAAA='
].join('');

function _decode() {
    const bin = (typeof atob === 'function')
        ? atob(CHARGEN_B64)
        : Buffer.from(CHARGEN_B64, 'base64').toString('binary');
    const out = new Uint8Array(2048);
    for (let i = 0; i < 2048; i++) out[i] = bin.charCodeAt(i);
    return out;
}

const CHARGEN_ROM = _decode();

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { CHARGEN_ROM };
} else if (typeof window !== 'undefined') {
    window.CHARGEN_ROM = CHARGEN_ROM;
}
